name: Build and Release Docker Image

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月的第一天执行一次
  workflow_dispatch:  # 手动触发支持

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone zhenxun_bot_docker Repository
      run: |
        git clone https://${{ secrets.GH_TOKEN }}@github.com/hui-ld/zhenxun_bot_docker.git /tmp/zhenxun_bot_docker

    - name: Get Latest Release Version
      id: get-latest-version
      run: |
        latest_release=$(curl -s https://api.github.com/repos/HibiKier/zhenxun_bot/releases/latest | jq -r .tag_name)
        echo "Latest release version: $latest_release"
        echo "latest_version=$latest_release" >> $GITHUB_ENV

    - name: Clone zhenxun_bot Repository
      run: |
        git clone https://github.com/HibiKier/zhenxun_bot.git /tmp/zhenxun_bot
        cp -r /tmp/zhenxun_bot_docker/* /tmp/zhenxun_bot/

    - name: Build and Push Docker Image
      run: |
        docker login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}" registry.cn-hangzhou.aliyuncs.com
        cd /tmp/zhenxun_bot
        docker build -t registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:${{ env.latest_version }} . 
        docker tag registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:${{ env.latest_version }} registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:latest
        docker push registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:${{ env.latest_version }}
        docker push registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:latest
