name: Build and Release Docker Image

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时执行一次
  workflow_dispatch:  # 手动触发支持

jobs:
  bt-product-release:
    runs-on: ubuntu-latest

    steps:
    # 检出当前仓库代码
    - name: Checkout the repository
      uses: actions/checkout@v2

    # 获取已处理的版本号
    - name: Get Processed Version
      id: get-processed-version
      run: |
        if [ -f processed_version.txt ]; then
          processed_version=$(cat processed_version.txt)
        else
          processed_version="none"
        fi
        echo "Processed version: $processed_version"
        echo "processed_version=$processed_version" >> $GITHUB_ENV

    # 获取 zhenxun_bot 最新发布版本号
    - name: Get Latest Release Version of zhenxun_bot
      id: get-latest-version
      run: |
        latest_release=$(curl -s https://api.github.com/repos/HibiKier/zhenxun_bot/releases/latest | jq -r .tag_name)
        echo "Latest release version is $latest_release"
        echo "latest_version=$latest_release" >> $GITHUB_ENV

    # 比较版本号
    - name: Check if New Version Exists
      id: version-check
      run: |
        if [ "${{ env.latest_version }}" != "${{ env.processed_version }}" ]; then
          echo "New version found: ${{ env.latest_version }}"
          echo "new_version=true" >> $GITHUB_ENV
          echo "::set-output name=new_version::true"
        else
          echo "No new version."
          echo "new_version=false" >> $GITHUB_ENV
          echo "::set-output name=new_version::false"

    # 确保 restart.sh 存在
    - name: Ensure restart.sh Exists
      run: |
        if [ ! -f restart.sh ]; then
          echo "Error: restart.sh not found"
          exit 1
        fi

    # 克隆 zhenxun_bot 并准备 Docker 构建
    - name: Clone zhenxun_bot and Prepare for Docker Build
      if: steps.version-check.outputs.new_version == 'true'
      run: |
        git clone --branch ${{ env.latest_version }} https://github.com/HibiKier/zhenxun_bot.git /tmp/zhenxun_bot
        mkdir -p /tmp/zhenxun_bot_docker/zhenxun/
        cp -r /tmp/zhenxun_bot/* /tmp/zhenxun_bot_docker/zhenxun/
        cp restart.sh /tmp/zhenxun_bot_docker/zhenxun/

    # 登录到阿里云容器镜像服务并构建镜像
    - name: Build and Push Docker Image
      if: steps.version-check.outputs.new_version == 'true'
      run: |
        docker login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}" registry.cn-hangzhou.aliyuncs.com
        cd /tmp/zhenxun_bot_docker
        docker build -t registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:${{ env.latest_version }} .
        docker tag registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:${{ env.latest_version }} registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:latest
        docker push registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:${{ env.latest_version }}
        docker push registry.cn-hangzhou.aliyuncs.com/starfishes/zhenxun-docker:latest
        echo "${{ env.latest_version }}" > processed_version.txt
